SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `team_player`;
DROP TABLE IF EXISTS `player`;
DROP TABLE IF EXISTS `team`;
DROP TABLE IF EXISTS `serie`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS `serie` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LEAGUE_ID` int(11) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `TEAM_1_ID` int(11) NOT NULL,
  `TEAM_2_ID` int(11) NOT NULL,
  `STATE` varchar(255) NOT NULL,
  `SCHEDULED_TIME` timestamp NULL DEFAULT NULL,
  `BEST_OF` int(11) DEFAULT NULL,
  `LEAGUE_NAME` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `NODE_NAME` varchar(255) DEFAULT NULL,
  `NODE_ID` int(11) DEFAULT NULL,
  `SERIES_ID` int(11) DEFAULT NULL,
  `ACTUAL_LOBBY_ID` int(11) DEFAULT NULL,
  `ACTUAL_MATCH_ID` int(11) DEFAULT NULL,
  `DETAIL` blob,
  PRIMARY KEY (`ID`),
  KEY `TEAM_1_ID` (`TEAM_1_ID`),
  KEY `TEAM_2_ID` (`TEAM_2_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10;


CREATE TABLE IF NOT EXISTS `team` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `TEAM_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `TEAM_ID` (`TEAM_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10;

CREATE TABLE IF NOT EXISTS `team_player` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEAM_ID` int(11) DEFAULT NULL,
  `PLAYER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10;

CREATE TABLE IF NOT EXISTS `player` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `ACCOUNT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10;


ALTER TABLE `team_player`
  ADD CONSTRAINT `TEAM_PLAYER_ibfk_1` FOREIGN KEY (`TEAM_ID`) REFERENCES `team` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `TEAM_PLAYER_ibfk_2` FOREIGN KEY (`PLAYER_ID`) REFERENCES `player` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `serie`
  ADD CONSTRAINT `SERIE_ibfk_1` FOREIGN KEY (`TEAM_1_ID`) REFERENCES `team` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `SERIE_ibfk_2` FOREIGN KEY (`TEAM_2_ID`) REFERENCES `team` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

